env:
  - FLASK_APP=main.py
dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database pusheen;' -U postgres

script:
  - python3 create_db.py
  - python3 test.py -v
